backend:
  name: github
  repo: ezermanihuruk/galeri-moses
  branch: main
  base_url: https://decap-oauth.vercel.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Galeri Foto"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Foto", name: "title", widget: "string", required: false }
      - { label: "Kategori", name: "category", widget: "select", options: ["Black and White", "Stage", "Sport", "Human", "Event", "Arsitektur"], required: true }
      - { label: "File Gambar", name: "image", widget: "image", required: true }
      - { label: "Caption / Deskripsi Foto", name: "caption", widget: "text", required: false }
