backend:
  name: github
  repo: ezermanihuruk/galeri-moses
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Galeri Foto"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Foto", name: "title", widget: "string" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Black and White", "Stage", "Sport", "Human", "Event", "Arsitektur"] }
      - { label: "File Gambar", name: "image", widget: "image" }
      - { label: "Caption / Deskripsi Foto", name: "caption", widget: "text" }
